### ISSUE TITLE
conflict between prettier and eslint configs

### ISSUE THREAD

**Issue by mccullochk** [TwoStoryRobot/eslint-config#15]
eslint throws a bunch of indentation errors about indentations introduced by prettier.

<img width="589" alt="screen shot 2018-05-18 at 3 31 53 pm" src="https://user-images.githubusercontent.com/15054821/40260647-a00be358-5ab0-11e8-83e9-0afe6cdb1d44.png">

Potential fix would be to add [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier#installation) which turns off all rules that might conflict with Prettier.

Two add to our config specs, change the following in `index.js`:
```diff
- extends: ['eslint:recommended', 'plugin:jest/recommended']
+ extends: ['eslint:recommended', 'plugin:jest/recommended', 'prettier']
```

**Comment by mccullochk** [comment]
@TwoStoryRobot/devs, I haven't looked into this that carefully yet. I am however curious whether anyone else has been encountering these warnings on repos that we've pull in both this and our `@twostoryrobot/prettier-config`?

**Comment by chadfawcett** [comment]
I haven't run into any issues, but @calebissharp ran into #12

**Comment by calebissharp** [comment]
Would there be any negatives to adding this? It would be better than having to manually update the eslint or prettier config every time we run into one of these issues.

**Comment by jonotron** [comment]
I also have not encountered this.

I feel like extending prettier in `eslint-config` here would create an unnecessary dependency on prettier. **However**, since this is our repo and we almost always do it with prettier, I'm in favour of imposing an opinion with this package :)

**Comment by mccullochk** [comment]
Hmm.. Funny. I wonder why I'm encountering this problem then.

**Comment by calebissharp** [comment]
It looks like `prettier` and `eslint` are clashing with each other over with `switch` formatting. `eslint` wants the cases to be vertically aligned with `switch`, while `prettier` wants indentation.

**Comment by calebissharp** [comment]
Yeah, I'll take a stab at it
