### ISSUE TITLE
CRA pins eslint which causes issues with the unpinned peer dependency

### ISSUE THREAD

**Issue by chadfawcett** [TwoStoryRobot/eslint-config#18]
create-react-app pins the eslint version as a direct dependency which results in issues when we install a different version to satisfy the peer dependency of this package. CRA says eslint should not be installed manually, but their installation is not hoisted for use by our package scripts.

We have a couple options:
1. make `eslint` a dependency of this package
2. recommend installing the `eslint` version that CRA uses (not recommended by CRA and would be annoying to remember when Renovate tries to bump the version)
3. See if CRA's eslint config satisfies our own. If it does, we don't need to add our own eslint config for CRA projects.

**Comment by mccullochk** [comment]
I recommend we look into # 3 first then if need be resort to # 1.

**Comment by jonotron** [comment]
This might be a bit unrelated... but I find CRA to be kind of a pain. The dependencies never seem to be up to date (e.g. Jest), and some things don't work as well as if we had installed them ourselves (e.g. Jest in a mono front/back repo). Maybe we could move to Parcel + manual packages instead?

**Comment by mccullochk** [comment]
I'd be open to trying out a different tool. I think we've ran into a decent number of edges with CRA now.

**Comment by chadfawcett** [comment]
I'm open to trying it but I'm hesitant to roll our own starter because of the maintenance overhead. I haven't found CRA to be that bad for what we get from it. We've been able to find solutions for the problems we've run into I think.

**Comment by chrisfosterelli** [comment]
This is solved by the latest versions of npm when our eslint-config is installed correctly on CRA projects as long as they are within a compatible peer dependency range.
