### ISSUE TITLE
Rule Proposal: `prefer-const`

### ISSUE THREAD

**Issue by chadfawcett** [TwoStoryRobot/eslint-config#19]
I propose that we use the [prefer-const](https://eslint.org/docs/rules/prefer-const) rule so we don't have to worry about let variables that aren't reassigned.

I **think** when the team started using let and const we mentioned that a good practice would be to always use const when the variable doesn't change. This wasn't formal or written down anywhere, so I think this rule will help.

Can I get a vote (👍or 👎) from @TwoStoryRobot/devs and @TwoStoryRobot/students?

**Comment by chrisfosterelli** [comment]
Sounds like consensus!

**Comment by chrisfosterelli** [comment]
Closed in favor of #23
