### ISSUE TITLE
Proposal: incorporate rules for internal styles we already maintain

### ISSUE THREAD

**Issue by chrisfosterelli** [TwoStoryRobot/eslint-config#23]
I've identified a few rules that exist which we already follow:

- [no-var](https://eslint.org/docs/rules/no-var.html)
- [object-shorthand](https://eslint.org/docs/rules/object-shorthand.html)
- [prefer-arrow-callback](prefer-arrow-callback)
- [no-duplicate-imports](https://eslint.org/docs/rules/no-duplicate-imports.html)
- [dot-notation](https://eslint.org/docs/rules/dot-notation#require-dot-notation-dot-notation)
- [prefer-const](https://eslint.org/docs/rules/prefer-const.html)
- [no-multiple-empty-lines](https://eslint.org/docs/rules/no-multiple-empty-lines.html)

We could add these if we liked. **Note**: I haven't recently verified that some of these are not defaults, but pretty sure I got this list originally because they were not enabled for us.

**Comment by chadfawcett** [comment]
@chrisfosterelli Not sure if you were looking for review yet, but these look good to me.

**Comment by calebissharp** [comment]
I think we can also add the `quotes: 'single'` rule.

**Comment by chrisfosterelli** [comment]
Cool! I don't have bandwidth to do a PR right now but I wanted to migrate this from where it was originally in notion so we are tracking it 😄
